server:
  port: 19093

spring:
  application:
    name: user
  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
  jpa:
    properties:
      hibernate:
        default_schema: users