server:
  port: 19100

spring:
  application:
    name: user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: users
  datasource:
    url: jdbc:postgresql://localhost:5432/4IRBNB
    username: postgres
    password: fourirbnb
    driver-class-name: org.postgresql.Driver